---
- name: install | Install GPFS SMB packages
  yum:
   name: "{{ scale_install_all_packages }}"
   state: present
   disable_gpg_check: "{{ scale_disable_gpgcheck }}"
  when: inventory_hostname in scale_smb_node_list
