---
#
# Install or update RPMs
#
- name: upgrade | Initialize
  set_fact:
    scale_disable_gpgcheck: "no"

- name: upgrade | Disable gpg check
  set_fact:
    scale_disable_gpgcheck: "yes"
  when: scale_version < '5.0.4.0'

- name: upgrade | Upgrade GPFS Zimon packages
  yum:
    name: "{{ scale_install_all_packages }}"
    state: latest
    update_only: yes
    disable_gpg_check: "{{ scale_disable_gpgcheck }}"
  when: ansible_pkg_mgr == 'yum'


- name: upgrade | Upgrade GPFS Zimon packages
  dnf:
    name: "{{ scale_install_all_packages }}"
    state: latest
    update_only: yes
    disable_gpg_check: "{{ scale_disable_gpgcheck }}"
  when: ansible_pkg_mgr == 'dnf'
