---
# defaults file for remote_mount
debug: false
forceRun: false

# retries - 3 minutes (36 x 5 seconds)
restapi_retries_count: 36
restapi_retries_delay: 5

client_cluster_gui_port: 443
storage_cluster_gui_port: 443

scalemgmt_endpoint: "scalemgmt/v2"
remote_mount_endpoint: "{{ scalemgmt_endpoint }}/remotemount"

# Storage filesystem
access_mount_attributes: "rw"

# If Accessing/Client Cluster dont have GUI, it will use CLI
client_cluster_no_gui: False

# Client Cluster (Access) is downloding the pubkey from Owning cluster and importing it.
storage_cluster_pub_key_location: "/tmp/storage_cluster_public_key.pub"

# Unmounts, remove the filesystem, and also the connection between Accessing/Client cluster and Owner/Storage Cluster.
# This only works if both systems have GUI/RESTAPI interface
cleanup_remote_mount: false