---
# This file is mandatory to import and it will load scale 
# inventory variable form vars/scale_clusterdefinition.json.
- import_playbook: "set_json_variables.yml"

- hosts: scale_node
  vars:
    - scale_install_directory_pkg_path: /opt/IBM/gpfs_cloud_rpms
  roles:
     - core/precheck
     - core/node
     - core/cluster
     - gui/precheck
     - gui/node
     - gui/cluster
     - gui/postcheck
     - zimon/precheck
     - zimon/node
     - zimon/cluster
     - zimon/postcheck
