---
- name: postcheck | Check if HDFS is running
  shell:
   cmd: "{{ scale_command_path }}/mmces service list|grep HDFS"
  register: scale_hdfs_status
  when: ansible_fqdn in scale_hdfs_node_list
  ignore_errors: true
  failed_when: false

- name: postcheck | Check if HDFS is running
  assert:
   that:
   - scale_hdfs_status.rc == 0
   fail_msg: "HDFS is not active on {{ ansible_hostname }}"
  when: ansible_fqdn in scale_hdfs_node_list
