---
#
# Install or update RPMs
#
- name: upgrade | Upgrade GPFS file audit logging packages
  yum:
    name: "{{ scale_install_all_packages }}"
    state: latest
    disable_gpg_check: "{{ scale_disable_gpgcheck }}"
  when: ansible_pkg_mgr == 'yum'

- name: upgrade | Upgrade GPFS file audit logging packages
  dnf:
    name: "{{ scale_install_all_packages }}"
    state: latest
    disable_gpg_check: "{{ scale_disable_gpgcheck }}"
  when: ansible_pkg_mgr == 'dnf'
