---
# Sanity check of configuration variables

- name: check | Count daemon processes
  command: pgrep mmfsd
  register: scale_daemon_procs
  changed_when: false
  failed_when: false

- name: check | Check if daemon is running
  set_fact:
    scale_daemon_running: "{{ true if scale_daemon_procs.rc == 0 else false }}"

# Make default variables available in hostvars
- name: check | Set default daemon nodename
  set_fact:
    scale_daemon_nodename: "{{ scale_daemon_nodename }}"
  when: hostvars[inventory_hostname].scale_daemon_nodename is undefined
