---
# tasks file for configure
- import_tasks: env_setup.yml
  when: scale_protocols is defined and scale_protocols.hdfs|bool
  tags: config

- import_tasks: configure.yml
  when: scale_protocols is defined and scale_protocols.hdfs|bool
  tags: config
