---
# Playbook sample for deploying IBM Spectrum Scale (GPFS) cluster using local package installation method.
- hosts: cluster01
  vars:
    - scale_version: 5.0.4.0
    - scale_install_localpkg_path: /root/Spectrum_Scale_Standard-5.0.4.0-x86_64-Linux-install
  roles:
    - core/precheck
    - core/node
    - core/cluster
    - core/postcheck
