---
#
# samples/playbook_json_ces.yml
#

# Playbook sample for deploying IBM Spectrum Scale (GPFS) cluster using
# inventory in JSON format. This sample also contains protocols (NFS & SMB),
# callhome and file audit logging.

# This file is mandatory to import and it will load inventory variables form
# samples/vars/scale_clusterdefinition.json
- import_playbook: set_json_variables.yml

- hosts: cluster01
  collections:
    - ibm.spectrum_scale
  vars:
    - scale_install_localpkg_path: /root/Spectrum_Scale_Advanced-5.1.0.0-x86_64-Linux-install
  roles:
    - core_prepare
    - core_install
    - core_configure
    - core_verify
    - gui_prepare
    - gui_install
    - gui_configure
    - gui_verify
    - perfmon_prepare
    - perfmon_install
    - perfmon_configure
    - perfmon_verify
    - callhome_prepare
    - callhome_install
    - callhome_configure
    - callhome_verify
    - nfs_prepare
    - nfs_install
    - nfs_configure
    - nfs_verify
    - smb_prepare
    - smb_install
    - smb_configure
    - smb_verify
    - fal_prepare
    - fal_install
    - fal_configure
    - fal_verify
