---
#
# samples/playbook_fileauditlogging.yml
#

# Playbook sample for deploying IBM Spectrum Scale (GPFS) cluster with File
# Audit Logging (FAL) enabled.

# Sample definitions can be found in samples/vars/fal_vars.yml

- hosts: cluster01
  collections:
    - ibm.spectrum_scale
  vars:
    - scale_version: 5.0.4.0
    - scale_install_localpkg_path: /root/Spectrum_Scale_Standard-5.0.4.0-x86_64-Linux-install
  pre_tasks:
    - include_vars: fal_vars.yml
  roles:
    - core_prepare
    - core_install
    - core_configure
    - core_verify
    - fal_prepare
    - fal_install
    - fal_configure
    - fal_verify
