---
#
# samples/playbook_callhome.yml
#

# Playbook sample for deploying IBM Spectrum Scale (GPFS) cluster with Call Home
# enabled. Additional variables need to be defined for this, it is recommended
# to use Ansible group variables for this purpose:
# https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html#assigning-a-variable-to-many-machines-group-variables

# Sample definitions can be found in samples/vars/callhome_vars.yml

- hosts: cluster01
  collections:
    - ibm.spectrum_scale
  vars:
    - scale_version: 5.0.4.0
    - scale_install_localpkg_path: /root/Spectrum_Scale_Standard-5.0.4.0-x86_64-Linux-install
  pre_tasks:
    - include_vars: callhome_vars.yml
  roles:
    - core_prepare
    - core_install
    - core_configure
    - core_verify
    - callhome_prepare
    - callhome_install
    - callhome_configure
    - callhome_verify
