---
#
# Install or update packages
#
- name: upgrade | Initialize
  set_fact:
    scale_disable_gpgcheck: "no"

- name: upgrade | Disable gpg check
  set_fact:
    scale_disable_gpgcheck: "yes"
  when: scale_version < '5.0.4.0'

- block:  ## when: rhel8 node
    - name: upgrade | Upgrade prereqs for GUI from source
      dnf:
        name: "{{ scale_gui_el8_prereqs }}"
        state: present
  when: ansible_distribution in scale_rhel_distribution and ansible_distribution_major_version == '8'

- name: upgrade | Upgrade GPFS GUI packages
  package:
    name: "{{ scale_install_all_packages }}"
    state: latest
    disable_gpg_check: "{{ scale_disable_gpgcheck }}"
