---
#
# Main file for Remote_Mount file.
#

#
# Checks that mandatory variables are set
#
- name: precheck
  include_tasks: precheck.yml

#
# This Block Unmounts, remove the filesystem and connection between Accessing/Client cluster and Owner/Storage Cluster.
#
- block: #when: scale_remotemount_cleanup_remote_mount | bool
    - name: Cleanup remote filesystem on Accessing/Client Cluster
      include_tasks: cleanup_remote_mount.yml
      when: scale_remotemount_cleanup_remote_mount | bool

    - meta: end_play
      when:
        - scale_remotemount_cleanup_remote_mount | bool
  when: scale_remotemount_cleanup_remote_mount | bool and scale_remotemount_client_no_gui == false

- block: #when: scale_remotemount_cleanup_remote_mount | true and
    - name: Cleanup remote filesystem on Accessing/Client Cluster - API-CLI
      include_tasks: cleanup_remote_mount_api_cli.yml

    - meta: end_play
      when:
        - scale_remotemount_cleanup_remote_mount | bool
  when: scale_remotemount_cleanup_remote_mount | bool and scale_remotemount_client_no_gui | bool

# This block is for systems with Scale GUI/RESTAPI on both Accessing cluster and Remote Cluster.
#
- block: # RESTAPI - when: scale_remotemount_client_no_gui == false
    - name: Main | Storage Cluster (owner) | Check Connectivity to Storage Cluster GUI
      uri:
        validate_certs: "{{ validate_certs_uri }}"
        force_basic_auth: yes
        url: https://{{ scale_remotemount_storage_gui_hostname }}:{{ storage_cluster_gui_port }}/{{ scalemgmt_endpoint }}/cluster
        method: GET
        user: "{{ scale_remotemount_storage_gui_username }}"
        password: "{{ scale_remotemount_storage_gui_password }}"
        body_format: json
        status_code:
          - 200
      register: storage_cluster_status
      run_once: True
      ignore_errors: true

    - name: Main | Storage Cluster (owner) | Conenction Refused Storage Cluster
      run_once: True
      fail:
        msg: "There is issues connection to GUI/RestAPI, http return code: {{ storage_cluster_status.status }}"
      when:
        - storage_cluster_status.status == -1

    - meta: end_play
      when:
        - storage_cluster_status.status == -1

    - name: Main | Storage Cluster (owner) | Unauthorized Storage Cluster
      run_once: True
      fail:
        msg: "The user is not authorized to access the Storage Cluster, http return code: {{ storage_cluster_status.status }}"
      when:
        - storage_cluster_status.status == 401

    - meta: end_play
      when:
        - storage_cluster_status.status == 401

    - name: Main | Client Cluster (access) | Check Connectivity to Client Cluster GUI
      uri:
        validate_certs: "{{ validate_certs_uri }}"
        force_basic_auth: yes
        url: https://{{ scale_remotemount_client_gui_hostname }}:{{ client_cluster_gui_port }}/{{ scalemgmt_endpoint }}/cluster
        method: GET
        user: "{{ scale_remotemount_client_gui_username }}"
        password: "{{ scale_remotemount_client_gui_password }}"
        body_format: json
        status_code:
          - 200
      register: access_cluster_status
      run_once: True
      ignore_errors: true

    - name: Main | Client Cluster (access) | Conenction Refused Client Cluster
      run_once: True
      fail:
        msg: "There is issues connection to GUI/RestAPI, http return code: {{ access_cluster_status.status }}"
      when:
        - access_cluster_status.status == -1

    - meta: end_play
      when:
        - access_cluster_status.status == -1

    - name: Main | Client Cluster (access) | Unauthorized Client Cluster
      run_once: True
      fail:
        msg: "The user is not authorized to access the Client Cluster, http return code: {{ access_cluster_status.status }}"
      when:
        - access_cluster_status.status == 401

    - meta: end_play
      when:
        - access_cluster_status.status == 401

    - name: Main | Client Cluster (access) | Check status of GPFS deamon (Nodeclass GUI_MGMT_SERVERS)
      uri:
        validate_certs: "{{ validate_certs_uri }}"
        force_basic_auth: true
        url: https://{{ scale_remotemount_client_gui_hostname }}:{{ client_cluster_gui_port }}/{{ scalemgmt_endpoint }}/nodes/GUI_MGMT_SERVERS/health/states?fields=component%2Cstate&filter=component%3DGPFS%2C
        method: GET
        user: "{{ scale_remotemount_client_gui_username }}"
        password: "{{ scale_remotemount_client_gui_password }}"
        body_format: json
        return_content: yes
        status_code:
          - 200
      register: clientcluster_gpfs_deamon_status
      run_once: True
      when: scale_remotemount_gpfsdemon_check | bool

    - name: Main | Client Cluster (access) | Print status of GPFS deamon on GUI_MGMT_SERVERS - Debug
      run_once: True
      ignore_errors: true
      debug:
        msg: "{{ clientcluster_gpfs_deamon_status.json.states[0].state }}"
      when:
        - scale_remotemount_gpfsdemon_check | bool
        - scale_remotemount_debug is defined
        - scale_remotemount_debug | bool

    - name: Main | Client Cluster (access) | GPFS Deamon on Client Cluster is down (Nodeclass GUI_MGMT_SERVERS)
      run_once: True
      assert:
        that:
          - "'HEALTHY' or 'DEGRADED' in storagecluster_gpfs_deamon_status.json.states[0].state"
        fail_msg: "'GPFS Deamon is NOT started on NodeClass GUI_MGMT_SERVERS"
        success_msg: "'GPFS Deamon is started on NodeClass GUI_MGMT_SERVERS"
      when: scale_remotemount_gpfsdemon_check | bool

    - name: Main | Storage Cluster (owning) | Check status of gpfs deamon on GUI_MGMT_SERVERS
      uri:
        validate_certs: "{{ validate_certs_uri }}"
        force_basic_auth: true
        url: https://{{ scale_remotemount_storage_gui_hostname }}:{{ storage_cluster_gui_port }}/{{ scalemgmt_endpoint }}/nodes/GUI_MGMT_SERVERS/health/states?fields=component%2Cstate&filter=component%3DGPFS%2C
        method: GET
        user: "{{ scale_remotemount_storage_gui_username }}"
        password: "{{ scale_remotemount_storage_gui_password }}"
        body_format: json
        return_content: yes
        status_code:
          - 200
      register: storagecluster_gpfs_deamon_status
      run_once: True
      when: scale_remotemount_gpfsdemon_check | bool

    - name: Main | storage Cluster (owning) | Print status of GPFS deamon on GUI_MGMT_SERVERS - Debug
      run_once: True
      ignore_errors: true
      debug:
        msg: "{{ storagecluster_gpfs_deamon_status.json.states[0].state }}"
      when:
        - scale_remotemount_gpfsdemon_check | bool
        - scale_remotemount_debug is defined
        - scale_remotemount_debug | bool

    - name: Main | Storage Cluster (owning) | GPFS Deamon on Storage Cluster is down (Nodeclass GUI_MGMT_SERVERS)
      run_once: True
      assert:
        that:
          - "'HEALTHY' or 'DEGRADED' in storagecluster_gpfs_deamon_status.json.states[0].state"
        fail_msg: "'GPFS Deamon is NOT started on NodeClass GUI_MGMT_SERVERS"
        success_msg: "'GPFS Deamon is started on NodeClass GUI_MGMT_SERVERS"
      when: scale_remotemount_gpfsdemon_check | bool

    - name: msg
      debug:
        msg: "Force Run was passed in, attempting to run remote_mount role regardless of whether the filesystem is configured."
      when: scale_remotemount_forceRun | bool
      run_once: True

    - name: Remote mount the filesystem's
      include_tasks: remotecluster.yml
  when:
    - scale_remotemount_client_no_gui == false

#
# This block is for systems with Scale GUI/RESTAPI only on Storage/Owning Cluster.
#
- block: # RESTAPI-CLI when: scale_remotemount_client_no_gui == true
  - name: Main | API-CLI | Storage Cluster (owner) | Check Connectivity to Storage Cluster GUI
    uri:
      validate_certs: "{{ validate_certs_uri }}"
      force_basic_auth: yes
      url: https://{{ scale_remotemount_storage_gui_hostname }}:{{ storage_cluster_gui_port }}/{{ scalemgmt_endpoint }}/cluster
      method: GET
      user: "{{ scale_remotemount_storage_gui_username }}"
      password: "{{ scale_remotemount_storage_gui_password }}"
      body_format: json
      status_code:
        - 200
    register: storage_cluster_status
    run_once: True
    ignore_errors: true

  - name: Main | API-CLI | Storage Cluster (owner) | Conenction Refused to Storage Cluster
    run_once: True
    fail:
      msg: "There is issues connection to GUI/RestAPI, http return code: {{ access_cluster_status.status }}"
    when:
      - storage_cluster_status.status == -1

  - meta: end_play
    when:
      - storage_cluster_status.status == -1

  - name: Main | API-CLI | Unauthorized Storage Cluster (owner)
    run_once: True
    debug:
      msg: "The user is not authorized to access the Storage Cluster, http return code: {{ storage_cluster_status.status }}"
    when:
      - storage_cluster_status.status == 401

  - meta: end_play
    when:
      - storage_cluster_status.status == 401

  - name: Main | API-CLI | Storage Cluster (owning) | Check status of gpfs deamon on GUI_MGMT_SERVERS
    uri:
      validate_certs: "{{ validate_certs_uri }}"
      force_basic_auth: true
      url: https://{{ scale_remotemount_storage_gui_hostname }}:{{ storage_cluster_gui_port }}/{{ scalemgmt_endpoint }}/nodes/GUI_MGMT_SERVERS/health/states?fields=component%2Cstate&filter=component%3DGPFS%2C
      method: GET
      user: "{{ scale_remotemount_storage_gui_username }}"
      password: "{{ scale_remotemount_storage_gui_password }}"
      body_format: json
      return_content: yes
      status_code:
        - 200
    register: storagecluster_gpfs_deamon_status
    run_once: True
    when: scale_remotemount_gpfsdemon_check | bool

  - name: Main | API-CLI |  Storage Cluster (owning) | Print status of GPFS deamon on GUI_MGMT_SERVERS - Debug
    run_once: True
    ignore_errors: true
    debug:
      msg: "{{ storagecluster_gpfs_deamon_status.json.states[0].state }}"
    when:
      - scale_remotemount_gpfsdemon_check | bool
      - scale_remotemount_debug is defined
      - scale_remotemount_debug | bool

  - name: Main | API-CLI | Storage Cluster (owning) | GPFS Deamon on Storage Cluster is down (Nodeclass GUI_MGMT_SERVERS)
    run_once: True
    assert:
      that:
        - "'HEALTHY' or 'DEGRADED' in storagecluster_gpfs_deamon_status.json.states[0].state"
      fail_msg: "'GPFS Deamon is NOT started on NodeClass GUI_MGMT_SERVERS"
      success_msg: "'GPFS Deamon is started on NodeClass GUI_MGMT_SERVERS"
    when: scale_remotemount_gpfsdemon_check | bool

  - name: Main | API-CLI | Force Run
    debug:
      msg: "Force Run was passed in, attempting to run remote_mount role regardless of whether the filesystem is configured"
    when: scale_remotemount_forceRun | bool

  - name: Main | API-CLI | Configure Remote Cluster
    include_tasks: remotecluster_api_cli.yml
    run_once: True

  - name: Main | API-CLI | Remote Mount the filesystems
    include_tasks: mount_filesystem_api_cli.yml
    run_once: True

  when:
    - scale_remotemount_client_no_gui | bool
