---
# Client Parameters
- name: "PreCheck | fail if not defined: scale_remotemount_client_gui_username"
  run_once: True
  fail:
    msg: "scale_remotemount_client_gui_username is not defined"
  when:
    - scale_remotemount_client_gui_username is undefined
    - scale_remotemount_client_no_gui == false

- name: "PreCheck | fail if not defined: scale_remotemount_client_gui_password"
  run_once: True
  fail:
    msg: "scale_remotemount_client_gui_password is not defined"
  when:
    - scale_remotemount_client_gui_password is undefined
    - scale_remotemount_client_no_gui == false

- name: "PreCheck | fail if not defined: scale_remotemount_client_gui_hostname"
  run_once: True
  fail:
    msg: "scale_remotemount_client_gui_hostname is not defined"
  when:
   - scale_remotemount_client_gui_hostname is undefined
   - scale_remotemount_client_no_gui == false

- name: "PreCheck | fail if not defined: scale_remotemount_client_filesystem_name"
  run_once: True
  fail:
    msg: "item.scale_remotemount_client_filesystem_name is not defined"
  when: item.scale_remotemount_client_filesystem_name is undefined
  loop: "{{ scale_remotemount_filesystem_name }}"

- name: "PreCheck | fail if not defined: scale_remotemount_client_remotemount_path"
  run_once: True
  fail:
    msg: "item.scale_remotemount_client_remotemount_path is not defined"
  when: item.scale_remotemount_client_remotemount_path is undefined
  loop: "{{ scale_remotemount_filesystem_name }}"

# Storage Parameters

- name: "PreCheck | fail if not defined: scale_remotemount_storage_gui_username"
  run_once: True
  fail:
    msg: "scale_remotemount_storage_gui_username is not defined"
  when: scale_remotemount_storage_gui_username is undefined

- name: "PreCheck | fail if not defined: scale_remotemount_storage_gui_password"
  run_once: True
  fail:
    msg: "scale_remotemount_storage_gui_password is not defined"
  when: scale_remotemount_storage_gui_password is undefined

- name: "PreCheck | fail if not defined: scale_remotemount_storage_gui_hostname"
  run_once: True
  fail:
    msg: "scale_remotemount_storage_gui_hostname is not defined"
  when: scale_remotemount_storage_gui_hostname is undefined

- name: "PreCheck | fail if not defined: scale_remotemount_storage_filesystem_name"
  run_once: True
  fail:
    msg: "item.scale_remotemount_storage_filesystem_name is not defined"
  when: item.scale_remotemount_storage_filesystem_name is undefined
  loop: "{{ scale_remotemount_filesystem_name }}"
