---
- name: install | Install GPFS nfs packages
  yum:
   name: "{{ scale_install_all_packages }}"
   state: present
   disable_gpg_check: "{{ scale_disable_gpgcheck }}"
  when: inventory_hostname in scale_nfs_nodes_list
